export enum ENV_KEYS {
  MODE = 'MODE',
  TG_BOT_TOKEN = 'TG_BOT_TOKEN',
  MONGODB_URL = 'MONGODB_URL',
  SEVER_PORT = 'SERVER_PORT',
  START_HOUR = 'START_HOUR',
  END_HOUR = 'END_HOUR',
  GOOGLE_ACCOUNT_EMAIL = 'GOOGLE_ACCOUNT_EMAIL',
  GOOGLE_CALENDAR_ID = 'GOOGLE_CALENDAR_ID',
  GOOGLE_SCOPE = 'GOOGLE_SCOPE',
}
