export enum ENV_KEYS {
  MODE = 'MODE',
  TG_BOT_TOKEN = 'TG_BOT_TOKEN',
  MONGODB_URL = 'MONGODB_URL',
  SEVER_PORT = 'SERVER_PORT',
  NOTION_TOKEN = 'NOTION_TOKEN',
  NOTION_DATABASE_ID = 'NOTION_DATABASE_ID',
  START_HOUR = 'START_HOUR',
  END_HOUR = 'END_HOUR',
}
